# Generated by Django 5.2.7 on 2025-11-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('books', 'Books'), ('electronics', 'Electronics'), ('clothing', 'Clothing'), ('furniture', 'Furniture'), ('tickets', 'Tickets'), ('kitchen', 'Kitchen Items'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
