# Generated by Django 5.2.7 on 2025-11-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_profile_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="nickname",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
