# Generated by Django 5.2.7 on 2025-11-14 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_post_category"),
        ("app", "0006_profile_nickname"),
    ]

    operations = []
