# Generated by Django 5.2.7 on 2025-11-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_merge_0006_post_category_0006_profile_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="onboarding_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="sustainability_interests",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
