# Generated by Django 5.2.7 on 2025-11-29 00:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_postflag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="hidden_from",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who should NOT be able to see this post.",
                related_name="posts_hidden_from",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
